name: SecondChance
main: @mainClass@
version: @version@
author: Roboboy

api-version: 1.13

commands:
  SecondChance:
    aliases: [chance, sc]
    description: Main command for SecondChance
    usage: /<command> <list|break|reload>
    permission: secondchance.maincommand
    permissions message: You don't have <permission>
